version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mernapp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: mongod --quiet

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mernapp
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mernapp
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  mernapp:
    driver: bridge